# Generated by Django 3.1.3 on 2020-11-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='task',
            name='recipient',
            field=models.CharField(default='admin', max_length=50, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='task',
            name='sponsor',
            field=models.CharField(default='admin', max_length=50, verbose_name='Отправитель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
